# Generated by Django 2.2 on 2019-05-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbhandler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='maxScore',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
