# Generated by Django 2.2 on 2019-05-12 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbhandler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbhandler.Course'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbhandler.User'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbhandler.Course'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbhandler.User'),
        ),
    ]
