# Generated by Django 2.2 on 2019-05-15 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbhandler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='course_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dbhandler.Course'),
            preserve_default=False,
        ),
    ]
