# Generated by Django 2.2 on 2019-05-28 13:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbhandler', '0002_testresult_maxscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
