# Generated by Django 2.2 on 2019-05-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbhandler', '0003_auto_20190528_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
